import {styleTags, tags as t} from "@lezer/highlight"

export const groqHighlighting = styleTags({
  "True False": t.bool,
  Null: t.null,
  "String/...": t.string,
  "DoubleString/...": t.string,
  "SingleString/...": t.string,
  StringEscape: t.escape,
  Number: t.number,
  LineComment: t.lineComment,
  Identifier: t.variableName,
  "PropertyPair/Identifier": t.propertyName,
  "DotAccess/Identifier": t.propertyName,
  "DerefAccess/Identifier": t.propertyName,
  "FunctionName/Identifier": t.function(t.variableName),
  "Namespace/Identifier": t.namespace,
  NamespaceSep: t.punctuation,
  Parameter: t.special(t.variableName),
  Everything: t.atom,
  "This Parent": t.self,
  "CompareOp EqualityOp": t.compareOperator,
  "AddOp MulOp Exp": t.arithmeticOperator,
  "And Or Not": t.logicOperator,
  "In Match Asc Desc": t.operatorKeyword,
  Pipe: t.controlOperator,
  Arrow: t.definitionOperator,
  Deref: t.derefOperator,
  "Ellipsis InclusiveRange": t.operator,
  '","  ":"': t.separator,
  '"(" ")"': t.paren,
  '"[" "]"': t.squareBracket,
  '"{" "}"': t.brace,
  '"."': t.derefOperator,
})
