name: Release Please

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      publish:
        description: Publish to NPM
        required: true
        default: false
        type: boolean

permissions:
  contents: read

jobs:
  release-please:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v3
        id: generate-token
        with:
          app-id: ${{ secrets.ECOSPARK_APP_ID }}
          private-key: ${{ secrets.ECOSPARK_APP_PRIVATE_KEY }}

      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ steps.generate-token.outputs.token }}

      # Publish to NPM on new releases
      - uses: actions/checkout@v6
        if: ${{ steps.release.outputs.releases_created == 'true' || github.event.inputs.publish == 'true' }}

      - uses: pnpm/action-setup@v5
        if: ${{ steps.release.outputs.releases_created == 'true' || github.event.inputs.publish == 'true' }}

      - uses: actions/setup-node@v6
        if: ${{ steps.release.outputs.releases_created == 'true' || github.event.inputs.publish == 'true' }}
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        if: ${{ steps.release.outputs.releases_created == 'true' || github.event.inputs.publish == 'true' }}
        run: pnpm install

      - name: Set publishing config
        if: ${{ steps.release.outputs.releases_created == 'true' || github.event.inputs.publish == 'true' }}
        run: pnpm config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

      - name: Publish to NPM
        if: ${{ steps.release.outputs.releases_created == 'true' || github.event.inputs.publish == 'true' }}
        run: pnpm -r publish --no-git-checks
        env:
          NPM_CONFIG_PROVENANCE: true
